name: "Greetings for PR & ISSUES"
on:
  issues:
    types: [opened, reopened]
  pull_request:
    types: [opened, reopened]      

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PR_AUTHOR: ${{ github.event.pull_request.actor }}
      PR_NUMBER: ${{ github.event.pull_request.number }}
    
    steps:
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: view the PR number
        run: |
          echo $PR_NUMBER
          echo $PR_AUTHOR
          echo "PR number = ${{ github.event.pull_request.number }}"
          echo "PR number = ${{ env.PR_NUMBER }}"
          
      - name: greeting2
        uses: actions/github-script@v2
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Hello World'
            })
